Updated lodash version
A number of individuals are getting this error when they run `npm test`

`.../checkpoint-express-review/node_modules/sequelize/lib/utils.js:38
      return _.mergeWith(a, b, function (objectValue, sourceValue) { ...
  TypeError: _.mergeWith is not a function`

The issue is that lodash wants to use the function mergeWith, which was added in version 4.0.1 but we are only requiring 3.7.0.
It seems like sequelize relies on having at least version 4.12.0 of lodash, but for some reason when it tries to use lodash it doesn't use its own version but the version in our package.json.

Updating the version to 4.12.0 fixes the problem, but its not clear if this is ultimately an issue with lodash's dependencies